spring.application.name=admin

# Database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/shieldglobalgroups?ssl=false
spring.datasource.username=postgres
spring.datasource.password=admin123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# File uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# JWT secret (keep this private)
jwt.secret=shieldglobal_super_secret_key_2026_do_not_share_xYzAbC

# Upload folder
file.upload-dir=uploads



